app = "Bbngxxapichaba7"  # اسم التطبيق على Fly.io

primary_region = "cdg"  # ريجن قريب (باريس)

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "15028"

[http_service]
  internal_port = 15028
  force_https = true

[[services]]
  protocol = "tcp"
  internal_port = 15028

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "10s"
    restart_limit = 0
    timeout = "2s"
